substitutions:
  firmware_version: "${version}"

packages:
  core: !include common.yaml

globals:
  - id: firmware_type
    type: std::string
    restore_value: no
    initial_value: '"bluetooth"'

ota:
  - platform: esphome
    password: "your-ota-password"
    on_ota_update:
      - lambda: |-
          id(show_status_message_msg) = "🔄 Updating to Bluetooth firmware...";
          id(show_status_message_duration) = 10;
      - script.execute: show_status_message
  - platform: http_request
    id: ota_http_request

update:
  - platform: http_request
    name: Firmware Update
    id: update_http_request
    source: https://modotabmount.modoco.io/firmware/latest/modotabmount.manifest.json
    filter:
      - lambda: |-
          for (const auto& firmware : manifest.firmwares) {
            if (firmware.name.find("bluetooth") != std::string::npos) {
              return true;
            }
          }
          return false;

bluetooth_proxy:
  active: true

button:
  - platform: factory_reset
    name: "Restart with Factory Default Settings"
    id: reset_button
    on_press:
      - if:
          condition:
            lambda: 'return id(factory_reset_confirmed);'
          then:
            - lambda: |-
                id(show_status_message_msg) = "✅ Factory reset initiated — switching to default firmware.";
                id(show_status_message_duration) = 10;
            - script.execute: show_status_message
            - delay: 2s
            - ota.perform:
                url: "https://modotabmount.modoco.io/firmware/${firmware_version}/modotabmount-default.bin"
          else:
            - lambda: |-
                id(show_status_message_msg) = "⚠️ Press again within 30s to confirm factory reset.";
                id(show_status_message_duration) = 30;
            - script.execute: show_status_message
            - globals.set:
                id: factory_reset_confirmed
                value: 'true'
            - delay: 30s
            - globals.set:
                id: factory_reset_confirmed
                value: 'false'
