packages:
  # Include all of the core configuration
  core: !include modotabmount.yaml

esphome:
  name: modotabmount
  # This will allow for project identification,
  # configuration and updates.
  project:
    name: modoco.modotabmount
    version: "1.0.5" # This will be replaced by the github workflows with the `release` version

# This should point to the public location of the yaml file that will be adopted.
# In this case it is the core yaml file that does not contain the extra things
# that are provided by this factory yaml file as the user does not need these once adopted.
dashboard_import:
  package_import_url: github://modo-co/modotabmount/modotabmount.yaml@main

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
esp32_improv:
  authorizer: none

# Sets up the improv via serial client for Wi-Fi provisioning.
# Handy if your device has a usb port for the user to add credentials when they first get it.
improv_serial:

# Include Web Server in Default firmware
web_server:
  port: 80

# Include BLE tracker
esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

# Include BT Proxy
bluetooth_proxy:
  active: true
  connection_slots: 3

# Used to pull OTA updates
http_request:
  buffer_size_rx: 2048
  buffer_size_tx: 2048

ota:
  - platform: http_request
    id: ota_http_request

update:
  - platform: http_request
    name: None
    id: update_http_request
    source: https://modotabmount.modoco.io/firmware/latest/modotabmount.manifest.json
